name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: 1eshkin
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: 1eshkin/chatbot:0.0.6
      - name: copy file via ssh
      uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          source: docker-compose.yml
          target: ${{ secrets.HOST_DIRECTORY }}
      - name: executing ssh commands on a remote server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_NAME }}
          username: ${{ secrets.HOST_USER }}
          key: ${{ secrets.HOST_KEY }}
          script: |
            scp docker-compose.yml ${{ secrets.HOST_USER }}@${{ secrets.HOST_NAME }}:/${{ secrets.HOST_DIRECTORY }}
            cd ${{ secrets.HOST_DIRECTORY }}
            docker compose pull
            docker compose up -d
